<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Desc' => '描述',
    'Create Coupon' => '生成优惠券',
    'Coupons' => '优惠券',
    'Condition' => '条件',
    'Result' => '结果',
    'Create At' => '创建时间',
    'Update At' => '更新时间',
    'Coupon' => '优惠券',
    'Start At' => '活动开始时间',
    'End At' => '活动结束时间',
    'Status' => '状态',
    'Star ID' => '店铺Id',
    'Total' => '创建数量',
    'Update' => '更新',
    'quantity' => '购买数量',
    'Categories' => '商品分类',
    'Type' => '优惠类型',
    'Number' => '优惠',
    'Shipping' => '邮费',
    'Total Price' => '订单总价',
    'Description' => '描述',
    'Coupon Info' => '基本信息',
    'Coupon Conditions' => '优惠生效条件',
    'Coupon Result' => '优惠',
    'Coupon No' => '优惠券号',


];