<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Payment Method' => '支付方式',
    'Payment Fee' => '税',
    'Payment' => '支付',
    'Transcation No' => '交易号码',
    'Create At' => '创建时间',
    'Update At' => '更新时间',
    'AliPay' => '支付宝',

];