<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Withdrawals' => '提款',
    'Withdrawal' => '提款',
    'Withdrawal Fee' => '手续费',
    'Withdrawal Account' => '提款账号',
    'Account Name' => '账户名',
    'Account Manage' => '账户管理',
    'Recharge' => '充值',
    'Recharges' => '充值',
    'Create At' => '创建时间',
    'Update At' => '更新时间',
    'Status' => '状态',
    'Money' => '钱',
    'Wait Shipment' => '待发货',
    'Wait Confirm' => '待收货',
    'Complete' => '订单完成',
    'Wait Refund' => '退货中',
    'Refund Failed' => '退货未通过',
    'Refund Pass' => '退货通过',
    'Order No' => '订单号',
    'Orders' => '订单',
    'Order' => '订单',
    'Update' => '更新',
    'Price' => '价格',
    'Qty' => '数量',
    'Picture' => '图片',
    'Item Name' => '货物名称',
    'Shipment' => '物流',

];