<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Refunds' => '退款',
    'Refund Fee' => '退款费用',
    'Reason' => '理由',
    'Memo' => '备注',
    'Create At' => '创建时间',
    'Update At' => '更新时间',
    'Status' => '状态',
    'Refund Log' => '退货日志',
    'Wait Check' => '等待审核',
    'Pass' => '审核通过',
    'Failed' => '审核未通过',
];