<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => '保存',
    'Items' => '商品',
    'Create Items' => '创建商品',
    'Base Info' => '基本信息',
    'Detailed Info' => '详细描述',
    'Other Info' => '其他信息',
    'Product Info' => '商品类型',
    'Product Image' => '商品图片',
    'Create' => '创建',
    'Update' => '更新',
    'Choose Action' => '选择操作',
    'delete' => '删除产品',
    'show' => '上架',
    'un_show' => '下架',
    'promote' => '促销',
    'un_promote' => '取消促销',
    'new' => '新品',
    'un_new' => '取消新品',
    'hot' => '热卖',
    'un_hot' => '取消热卖',
    'best' => '精品',
    'un_best' => '取消精品',
    'Create image dir fail.' => '创建文件夹失败',
    'Remove image fail.' => '移动文件夹失败',
    'save images to database fail.' => '保存图片到数据库失败',
    'delete image fail' => '删除图片失败',
    'Item Props' => '商品属性',
    'Create Item Props' => '创建商品属性',
    'Create Item Prop' => '创建商品属性',
    'Update Item Prop' => '更新商品属性',
    'Catalog' => '商品管理',
    'Item List' => '商品列表',
    'Create Item' => '创建商品',
    'Update Item: ' => '更新商品： ',
    'Please select Skus!' => '您需要选择所有的销售属性，才能组合成完整的规格信息!',
    'Every sku must have a value !' => '销售属性都必须有值!',
    'All of the props must be chosen' => '您需要选择所有的销售属性，才能组合成完整的规格信息。',
    'price' => '价格',
    'stock' => '库存数量',
    'Image(If update,Please upload first)'=>'图片（若更新,请先上传图片）',
    'The requested Item could not be found.'=>'您搜索的商品不存在',
    'There is no product'=>'没有商品',
];