<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Member Center' => '用户中心',
    'Member Information' => '用户信息',
    'My WishList' => '愿望清单',
    'Wishlist' => '愿望清单',
    'Delivery Address' => '收货地址',
    'Order' => '订单',
    'Order List' => '订单',
    'My Orders' => '摘要',
    'Tags' => '标签',
    'Title' => '标题',
    'Phone' => '手机号',
    'Is Default' => '默认地址',
    'Zip Code' => '邮政编码',
];
